trunk/common/modules/articles/models/ItemVideoGallery.php
<?php

namespace common\modules\articles\models;

use Yii;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "article_item_video_gallery".
 *
 * @property integer $id
 * @property string $video
 * @property string $type
 * @property string $caption
 * @property integer $item_id
 */
class ItemVideoGallery extends Articles
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article_item_video_gallery';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['video', 'type', 'item_id','category_id'], 'required'],
            [['video'], 'string'],
            [['item_id','category_id'], 'integer'],
            [['type'], 'string', 'max' => 20],
            [['caption'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'video' => 'Video',
            'type' => 'Type',
            'caption' => 'Caption',
            'item_id' => 'Article',
        	'category_id' => 'Category'
        ];
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
    	return $this->hasOne(Items::className(), ['id' => 'item_id'])->from(Items::tableName() . ' AS item');
    }
    
    /*
     * Return array for Video Type
     * @return array
     */
    public function getVideoTypeSelect2()
    {
    	$videotype = [ "youtube" => "YouTube", "vimeo" => "Vimeo", "dailymotion" => "Dailymotion" ];
    
    	return $videotype;
    }
    
    public function search($params)
    {
    	$query = self::find();
    	$query->joinWith('item');
    	$dataProvider = new ActiveDataProvider([
    			'query' => $query,
    			'sort' => [
    					'defaultOrder' => [
    							'id' => SORT_DESC
    					],
    			],
    	]);
    	$this->load($params);
    
    	//     	if (!$this->validate()) {
    	//     		return $dataProvider;
    	//     	}
    
    	$query->andFilterWhere(['like', 'item.title', $this->item_id]);
    	return $dataProvider;
	}
}

trunk/common/modules/articles/controllers/ItemVideoGalleryController.php
<?php

namespace common\modules\articles\controllers;

use Yii;
use common\modules\articles\models\ItemVideoGallery;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * ItemVideoGalleryController implements the CRUD actions for ItemVideoGallery model.
 */
class ItemVideoGalleryController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ItemVideoGallery models.
     * @return mixed
     */
    public function actionIndex()
    {
    	$model = new ItemVideoGallery();
    	$dataProvider = $model->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        	'model' => $model	
        ]);
    }

    /**
     * Displays a single ItemVideoGallery model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ItemVideoGallery model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ItemVideoGallery();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        	return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ItemVideoGallery model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        	return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ItemVideoGallery model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ItemVideoGallery model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ItemVideoGallery the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ItemVideoGallery::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    public function actionCategoryArticles(){
    	$postData = Yii::$app->request->post();
    	$out = [];
    	if (isset($postData['depdrop_parents'])) {
    		$parents = $postData['depdrop_parents'];
    		$selected =$postData['depdrop_params'][0];
    		if ($parents != null) {
    			$categories = \common\modules\articles\models\Items::find()->where(['type' => $parents[0] ])->all();
    			foreach($categories as $category){
    				$out[] = [
    						'id' => $category->id,
    						'name'=>ucwords($category->title)
    				];
    			}
    			echo Json::encode(['output'=>$out, 'selected'=>$selected>0?$selected:'']);
    			return;
    		}
    	}
    	echo Json::encode(['output'=>'', 'selected'=>'']);
    }
}

trunk/common/modules/articles/controllers/ItemsController.php
<?php

/**
 * @copyright Copyright &copy; Gogodigital Srls
 * @company Gogodigital Srls - Wide ICT Solutions
 * @website http://www.gogodigital.it
 * @github https://github.com/cinghie/yii2-articles
 * @license GNU GENERAL PUBLIC LICENSE VERSION 3
 * @package yii2-articles
 * @version 0.6.3
 */
namespace common\modules\articles\controllers;

use Yii;
use common\modules\articles\models\Items;
use common\modules\articles\models\ItemsSearch;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use common\models\Categories;
use yii\helpers\Json;
use common\modules\articles\models\Articles;
use yii\web\UploadedFile;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\modules\articles\models\ArticleTags;

/**
 * ItemsController implements the CRUD actions for Items model.
 */
class ItemsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => [
                            'index',
                            'create',
                            'update',
                            'delete',
                            'deleteimage',
                            'deletemultiple',
                            'changestate',
                            'activemultiple',
                            'deactivemultiple',
                            'category-products',
                            'type-category',
                            'upload-file'
                        ],
                        'roles' => [
                            '@'
                        ]
                    ],
                    [
                        'allow' => true,
                        'actions' => [
                            'view',
                            'category'
                        ],
                        'roles' => [
                            '?',
                            '@'
                        ]
                    ]
                ],
                'denyCallback' => function () {
                    throw new \Exception ('You are not allowed to access this page');
                }
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'changestate' => [
                        'post'
                    ],
                    'delete' => [
                        'post'
                    ],
                    'deleteImage' => [
                        'post'
                    ],
                    'deletemultiple' => [
                        'post'
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all Items models.
     *
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionIndex()
    {
        // Check RBAC Permission
        if ($this->userCanIndex()) {
            $searchModel = new ItemsSearch ();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider
            ]);
        } else {
            throw new ForbiddenHttpException ();
        }
    }

    /**
     * Displays a single Items model.
     *
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionView($alias = null)
    {
        $this->layout = "cms";
        $model = Items::find()->where(["alias" => $alias])->one();
        if ($model !== null) {
            $model->hits = $model->hits + 1;
            $model->save();
            $category = new \common\modules\articles\models\Categories ();
            $topCateogryItem = $category->getTopViewdItemsByCategory($model->catid, 'hits');
            $articleTags = $model->getArticleTags();
            $articleGallery = [$model->getImageUrl()];
            $articleImages = $model->imageGallery;
            foreach ($articleImages as $image) {
                $articleGallery[] = $image->getImageUrl();
            }
            return $this->render('view', [
                'model' => $model,
                'topCateogryItem' => $topCateogryItem,
                'articleTags' => $articleTags,
                'articleGallery' => $articleGallery
            ]);
        } else {
            throw new NotFoundHttpException ('The requested page does not exist.');
        }
    }

    /**
     * Creates a new Items model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionCreate()
    {
        // Check RBAC Permission
        if ($this->userCanCreate()) {
            $model = new Items ();

            if ($model->load(Yii::$app->request->post())) {
                // Set Modified as actual date
                $model->modified = "0000-00-00 00:00:00";

                // If alias is not set, generate it
                if ($_POST ['Items'] ['alias'] == "") {
                    $model->alias = $model->generateAlias($model->title);
                }
                if (!empty ($_POST ['Items'] ['tags'])) {
                    $tags = [];
                    foreach ($model->tags as $tagId) {
                        if ($tagId > 0) {
                            $tags [] = $tagId;
                        } else {
                            $articleTags = new ArticleTags ();
                            $articleTags->name = $tagId;
                            $articleTags->save();
                            $tags [] = $articleTags->id;
                        }
                    }
                    $model->tags = implode(",", $tags);
                }

                // Upload Image and Thumb if is not Null
                $imagePath = Yii::getAlias(Yii::$app->controller->module->itemImagePath);
                $thumbPath = Yii::getAlias(Yii::$app->controller->module->itemThumbPath);
                $imgNameType = Yii::$app->controller->module->imageNameType;
                $imgOptions = Yii::$app->controller->module->thumbOptions;
                $imgName = $model->title;
                $fileField = "image";

                // Create UploadFile Instance
                $image = $model->uploadFile($imgName, $imgNameType, $imagePath, $fileField);

                if ($model->save()) {

                    // upload only if valid uploaded file instance found
                    if ($image !== false) {
                        // save thumbs to thumbPaths
                        $model->createCustomThumbImages($image, $imagePath, $imgOptions, $thumbPath);
                    }

                    // Set Success Message
                    Yii::$app->session->setFlash('success', Yii::t('articles', 'Item has been created!'));

                    return $this->redirect([
                        'index'
                    ]);
                } else {

                    // Set Error Message
                    Yii::$app->session->setFlash('error', Yii::t('articles', 'Item could not be saved!'));

                    return $this->render('create', [
                        'model' => $model
                    ]);
                }
            } else {

                return $this->render('create', [
                    'model' => $model
                ]);
            }
        } else {
            throw new ForbiddenHttpException ();
        }
    }

    /**
     * Updates an existing Items model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        // Check RBAC Permission
        if ($this->userCanUpdate($id)) {
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post())) {

                // Set Modified as actual date
                $model->modified = date("Y-m-d H:i:s");

                // Set Modified by User
                $model->modified_by = Yii::$app->user->identity->id;

                // If alias is not set, generate it
                if ($_POST ['Items'] ['alias'] == "") {
                    $model->alias = $model->generateAlias($model->title);
                }
                if (!empty ($_POST ['Items'] ['tags'])) {
                    $tags = [];
                    foreach ($model->tags as $tagId) {
                        if ($tagId > 0) {
                            $tags [] = $tagId;
                        } else {
                            $articleTags = new ArticleTags ();
                            $articleTags->name = $tagId;
                            $articleTags->save();
                            $tags [] = $articleTags->id;
                        }
                    }
                    $model->tags = implode(",", $tags);
                }

                // Upload Image and Thumb if is not Null
                $imagePath = Yii::getAlias(Yii::$app->controller->module->itemImagePath);
                $thumbPath = Yii::getAlias(Yii::$app->controller->module->itemThumbPath);
                $imgNameType = Yii::$app->controller->module->imageNameType;
                $imgOptions = Yii::$app->controller->module->thumbOptions;
                $imgName = $model->title;
                $fileField = "image";

                // Create UploadFile Instance
                $image = $model->uploadFile($imgName, $imgNameType, $imagePath, $fileField);

                if ($model->image == false && $image === false) {

trunk/common/modules/articles/views/item-video-gallery/_form.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package yii2-articles
* @version 0.6.3
*/

use common\modules\articles\assets\ArticlesAsset;
use kartik\widgets\ActiveForm;
use kartik\widgets\FileInput;
use kartik\widgets\Select2;
use yii\helpers\Html;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;

// Load Articles Assets
ArticlesAsset::register($this);
$asset = $this->assetBundles['common\modules\articles\assets\ArticlesAsset'];

// Load info
$select2videotype = $model->getVideoTypeSelect2();
$select2articles = $model->getItemsSelect2();
$articleType 	  = \common\modules\articles\models\Categories::getArticleTypes();


?>

<div class="attachments-form">

    <?php $form = ActiveForm::begin([
        'options' => [
            'enctype'=>'multipart/form-data'
        ],
    ]); ?>

    <div class="row">

        <div class="col-lg-12">
        
<div class="col-lg-6">
                        
                        	<?= $form->field($model, 'video', [
									'addon' => [
										'prepend' => [
											'content'=>'<i class="glyphicon glyphicon-film"></i>'
										]
									]
							])->textInput(['maxlength' => true]) ?>
                        
                        	<?= $form->field($model, 'type')->widget(Select2::classname(), [
                                    'data' => $select2videotype,
                                    'addon' => [
										'prepend' => [
											'content'=>'<i class="glyphicon glyphicon-film"></i>'
										]
									],
                            ]); ?>   
                            
                        </div> <!-- end col-lg-6 -->
                        
                        <div class="col-lg-6">
                            
                            <?= $form->field($model, 'caption', [
									'addon' => [
										'prepend' => [
											'content'=>'<i class="glyphicon glyphicon-facetime-video"></i>'
										]
									 ]
							])->textarea(['maxlength' => 255,'rows' => 6]) ?>
                            
                            <?= 
	                        	$form->field($model, 'category_id')->widget(Select2::classname(), [
	                        			'data' => $articleType,
	                        			'language' => 'eg',
	                        			'options' => ['placeholder' => 'Select Article Type'],
	                        			'pluginOptions' => [
	                        					'allowClear' => true
	                        			],
	                        	]);
                        	
                        	?>
                        	<?=
                        		Html::hiddenInput('input-article_type', $model->category_id, ['id'=>'input-article_type']);
                        	?>
                            <?=
	                            $form->field($model, 'item_id')->widget(DepDrop::classname(), [
	                            		'options' => ['id'=>'itemvideogallery-item_id'],
	                            		'pluginOptions'=>[
	                            				'initialize' => true,
	                            				'depends'=>['itemvideogallery-category_id'],
	                            				'placeholder' => 'Select Cagtegory...',
	                            				'url' => Url::to(['/articles/item-image-gallery/category-articles']),
	                            				'params'=>['input-article_type']
	                            		]
	                            ]);
                            ?>
            
                        
                        
                    
         </div> <!-- #image -->

            <div class="col-lg-12">

                <div class="form-group">
                    <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                </div>

            </div>

        </div>

    </div>

    <?php ActiveForm::end(); ?>

</div>

trunk/common/modules/articles/views/item-video-gallery/create.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package articles
* @version 0.6.3
*/

use yii\helpers\Html;

// Set Title and Breadcrumbs
$this->title = 'Create Item Video Gallery';
$this->params['breadcrumbs'][] = ['label' => Yii::t('articles', 'Item Video Galleries'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

// Render Yii2-Articles Menu
echo Yii::$app->view->renderFile('@common/modules/articles/views/default/_menu.php');

?>
<div class="item-video-gallery-create">

    <?php if(Yii::$app->getModule('articles')->showTitles): ?>
        <div class="page-header">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
    <?php endif ?>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

trunk/common/modules/articles/views/item-video-gallery/index.php
<?php

/**
 *
 * @copyright Copyright &copy; Gogodigital Srls
 *            @company Gogodigital Srls - Wide ICT Solutions
 *            @website http://www.gogodigital.it
 *            @github https://github.com/cinghie/yii2-articles
 * @license GNU GENERAL PUBLIC LICENSE VERSION 3
 * @package articles
 * @version 0.6.3
 *         
 */

use common\modules\articles\assets\ArticlesAsset;
use kartik\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;

// Load Articles Assets
ArticlesAsset::register ( $this );
$asset = $this->assetBundles ['common\modules\articles\assets\ArticlesAsset'];

// Set Title and Breadcrumbs
$this->title = 'Item Video Galleries';
$this->params['breadcrumbs'][] = $this->title;

// Render Yii2-Articles Menu
echo Yii::$app->view->renderFile ( '@common/modules/articles/views/default/_menu.php' );

// Register action buttons js
$this->registerJs ( '
    $(document).ready(function()
    {
        $("a.btn-update").click(function() {
            var selectedId = $("#w2").yiiGridView("getSelectedRows");

            if(selectedId.length == 0) {
                alert("' . Yii::t ( "articles", "Select at least one item" ) . '");
            } else if(selectedId.length>1){
                alert("' . Yii::t ( "articles", "Select only 1 item" ) . '");
            } else {
                var url = "' . Url::to ( [ 
		'/articles/item-video-gallery/update' 
] ) . '&id="+selectedId[0];
                window.location.href= url;
            }
        });
        $("a.btn-active").click(function() {
            var selectedId = $("#w2").yiiGridView("getSelectedRows");

            if(selectedId.length == 0) {
                alert("' . Yii::t ( "articles", "Select at least one item" ) . '");
            } else {
                $.ajax({
                    type: \'POST\',
                    url : "' . Url::to ( [ 
		'/articles/item-video-gallery/activemultiple' 
] ) . '?id="+selectedId,
                    data : {ids: selectedId},
                    success : function() {
                        $.pjax.reload({container:"#w2"});
                    }
                });
            }
        });
        $("a.btn-deactive").click(function() {
            var selectedId = $("#w2").yiiGridView("getSelectedRows");

            if(selectedId.length == 0) {
                alert("' . Yii::t ( "articles", "Select at least one item" ) . '");
            } else {
                $.ajax({
                    type: \'POST\',
                    url : "' . Url::to ( [ 
		'/articles/item-video-gallery/deactivemultiple' 
] ) . '?id="+selectedId,
                    data : {ids: selectedId},
                    success : function() {
                        $.pjax.reload({container:"#w2"});
                    }
                });
            }
        });
        $("a.btn-delete").click(function() {
            var selectedId = $("#w2").yiiGridView("getSelectedRows");

            if(selectedId.length == 0) {
                alert("' . Yii::t ( "articles", "Select at least one item" ) . '");
            } else {
                var choose = confirm("' . Yii::t ( "articles", "Do you want delete selected items?" ) . '");

                if (choose == true) {
                    $.ajax({
                        type: \'POST\',
                        url : "' . Url::to ( [ 
		'/articles/item-video-gallery/deletemultiple' 
] ) . '&id="+selectedId,
                        data : {ids: selectedId},
                        success : function() {
                            $.pjax.reload({container:"#w1"});
                        }
                    });
                }
            }
        });
        $("a.btn-preview").click(function() {
            var selectedId = $("#w2").yiiGridView("getSelectedRows");

            if(selectedId.length == 0) {
                alert("' . Yii::t ( "articles", "Select at least one item" ) . '");
            } else if(selectedId.length>1){
                alert("' . Yii::t ( "articles", "Select only 1 item" ) . '");
            } else {
                var url = "' . Url::to ( [ 
		'/articles/item-video-gallery/view' 
] ) . '&id="+selectedId[0];
                window.open(url,"_blank");
            }
        });
    });
' );

?>

<div class="item-video-gallery-index">

	<?php if(Yii::$app->getModule('articles')->showTitles): ?>
		<div class="page-header">
			<h1><?= Html::encode($this->title) ?></h1>
		</div>
	<?php endif ?>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    
    <!-- item-video-gallery Grid -->
    <div class="item-video-gallery-grid">

		<?php Pjax::begin() ?>

        <?= GridView::widget([
            'dataProvider'=> $dataProvider,
            'filterModel' => $model,
            'pjaxSettings'=>[
                'neverTimeout' => true,
            ],
            'columns' => [
				[
					'class' => '\kartik\grid\CheckboxColumn'
				],
            		[
                	'attribute' => 'id',
                	'format' => 'html',
                	'hAlign' => 'center',
                	'value' => function ($model) {
                    $url = urldecode(Url::toRoute(['/articles/item-video-gallery/update', 'id' => $model->id]));
                    	return Html::a($model->id,$url);
                	}
            	],
            	'video:ntext',
            	'type',
            	'caption',
            	[
            			'attribute' => 'item_id',
            			'format' => 'html',
            			'hAlign' => 'center',
            			'value' => 'item.name',
            			'value' => function ($data) {
            			$url = urldecode(Url::toRoute(['items/update',
            					'id' =>  $data->item_id,
            			]));
            			$cat = isset($data->item->title) ? $data->item->title : "";
            		
            			if($cat!="") {
            				return Html::a($cat,$url);
            			} else {
            				return Yii::t('articles', 'NA');
            			}
            			}
            		],
            	[
            	'class' => 'yii\grid\ActionColumn',
            	'template' => '{update} {delete}',
            	],

			],
            'responsive' => true,
            'hover' => true,
			'panel' => [
				'heading'    => '<h3 class="panel-title"><i class="fa fa-folder-open"></i></h3>',
				'type'       => 'success',
                'before'     => '<span style="margin-right: 5px;">'.
                    Html::a('<i class="glyphicon glyphicon-plus"></i> '.Yii::t('articles', 'New'),
                        ['create'], ['class' => 'btn btn-success']
                    ).'</span><span style="margin-right: 5px;">'.
                    Html::a('<i class="glyphicon glyphicon-pencil"></i> '.Yii::t('articles', 'Update'),
                        '#', ['class' => 'btn btn-update btn-warning']
                    ).'</span><span style="margin-right: 5px;">'.
                    Html::a('<i class="fa fa-eye"></i> '.Yii::t('articles', 'Preview'),
                        '#', ['class' => 'btn btn-preview btn-info']
                    ).'</span><span style="float: right; margin-right: 5px;">',
				'after' => Html::a('<i class="glyphicon glyphicon-repeat"></i> '.
                    Yii::t('articles', 'Reset Grid'), ['index'], ['class' => 'btn btn-info']
				),
				'showFooter' => false
			],
        ]); ?>

		<?php Pjax::end() ?>

	</div>

</div>

trunk/common/modules/articles/views/item-video-gallery/update.php
<?php

/**
* @copyright Copyright &copy; Gogodigital Srls
* @company Gogodigital Srls - Wide ICT Solutions 
* @website http://www.gogodigital.it
* @github https://github.com/cinghie/yii2-articles
* @license GNU GENERAL PUBLIC LICENSE VERSION 3
* @package articles
* @version 0.6.3
*/

use yii\helpers\Html;

// Set Title and Breadcrumbs
$this->title = Yii::t('articles', 'Update {modelClass}: ', ['modelClass' => 'Item Image',]) . ' ' . $model->caption;
$this->params['breadcrumbs'][] = ['label' => Yii::t('articles', 'Attachments'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

// Render Yii2-Articles Menu
echo Yii::$app->view->renderFile('@common/modules/articles/views/default/_menu.php');

?>
<div class="item-video-gallery-update">

    <?php if(Yii::$app->getModule('articles')->showTitles): ?>
        <div class="page-header">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
    <?php endif ?>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

trunk/common/modules/articles/views/item-video-gallery/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model cinghie\articles\models\ItemVideoGallery */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Item Video Galleries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-video-gallery-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'video:ntext',
            'type',
            'caption',
            'item_id',
        ],
    ]) ?>

</div>