trunk/backend/controllers/DealsController.php
<?php
namespace backend\controllers;

use Yii;


use common\models\Coupons;
use backend\models\CouponsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\Logs;
use backend\models\DealUrls;
use yii\web\UploadedFile;

/**
 * DealsController implements the CRUD actions for Deals model.
 */
class DealsController extends Controller
{
	
	public function beforeAction($action) {
		$this->enableCsrfValidation = false;
		return parent::beforeAction($action);
	}
	
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


 public function actionOnline()
    {
        $searchModel = new CouponsSearch();
		$searchModel->moved = 1;
		$searchModel->type = 2;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('//coupons//index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }



	 public function actionStage()
    {
        $searchModel = new CouponsSearch();
		$searchModel->moved = 0;
		$searchModel->type = 2;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('//coupons/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }



	 /**
     * Creates a new Coupons model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Coupons();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			
				
						
			$model->created = date('Y-m-d h:i:s');
			
			$model->save();
			
			// save user logs data in user_logs table
			$logs_model = new Logs();
			
			$user_logs = array('model'=>'Coupons','action'=>'Create','activity' => $model->title.' is added','action_id'=>$model->id);
			$logs_model->saveUserLogs($user_logs);
			
			Yii::$app->session->setFlash('success', 'Coupons is successfully saved');
            return $this->redirect(['index']);
			
        } else {
            return $this->render('//coupons/create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Coupons model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {	
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->created = date('Y-m-d h:i:s');
			
			$model->save();
			
			// save user logs data in user_logs table
			$logs_model = new Logs();
			
			$user_logs = array('model'=>'Coupons','action'=>'Update','activity' => $model->title.' is added','action_id'=>$model->id);
			$logs_model->saveUserLogs($user_logs);
			
			Yii::$app->session->setFlash('success', 'Coupons is successfully saved');
			if($model->moved){
            return $this->redirect(['online']);
			}else{
				     return $this->redirect(['stage']);
			}
        } else {
            return $this->render('//coupons/update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Coupons model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
		
		$this->findModel($id)->delete();
		
		// save user logs data in user_logs table
			$logs_model = new Logs();
			
			$user_logs = array('model'=>'Coupons','action'=>'Delete','activity' => $model->title.' is deleted','action_id'=>$model->id);
			$logs_model->saveUserLogs($user_logs);	
                        
            Yii::$app->session->setFlash('success', 'Blogs is successfully delete');
		if($model->moved){
            return $this->redirect(['online']);
			}else{
				     return $this->redirect(['stage']);
			}
        
    }

  

    /**
     * Displays a single Deals model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    // /**
    //  * Creates a new Deals model.
    //  * If creation is successful, the browser will be redirected to the 'view' page.
    //  * @return mixed
    //  */
    // public function actionCreate()
    // {
    //     $model = new Deals();

    //     if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			
	// 		// save main image
	// 		$model->main_image = UploadedFile::getInstance($model,'main_image');
	// 		if(!empty($model->main_image)){
	// 			$imageName = time().uniqid();
				
	// 			$path = Yii::getAlias('@frontend') .'/web/';
				
	// 			$model->main_image->saveAs($path.'uploads/deals/'.$imageName.'.'.$model->main_image->extension);
				
				
	// 			$model->image = $imageName.'.'.$model->main_image->extension;
				
	// 		}
						
	// 		$model->created = date('Y-m-d h:i:s');
			
	// 		$model->save();
			
	// 		// save user logs data in user_logs table
	// 		$logs_model = new Logs();
			
	// 		$user_logs = array('model'=>'Deals','action'=>'Create','activity' => $model->title.' is added','action_id'=>$model->id);
	// 		$logs_model->saveUserLogs($user_logs);
			
	// 		Yii::$app->session->setFlash('success', 'Deals is successfully saved');
    //         return $this->redirect(['index']);
			
    //     } else {
    //         return $this->render('create', [
    //             'model' => $model,
    //         ]);
    //     }
    // }

    // /**
    //  * Updates an existing Deals model.
    //  * If update is successful, the browser will be redirected to the 'view' page.
    //  * @param integer $id
    //  * @return mixed
    //  */
    // public function actionUpdate($id)
    // {
    //     $model = $this->findModel($id);

    //      if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            	
	// 		// save main image
	// 		$model->main_image = UploadedFile::getInstance($model,'main_image');
			
	// 		if(!empty($model->main_image)){
				
	// 			$imageName = time().uniqid();
				
	// 			$path = Yii::getAlias('@frontend') .'/web/';
				
	// 			$model->main_image->saveAs($path.'uploads/deals/'.$imageName.'.'.$model->main_image->extension);
				
				
	// 			$model->image = $imageName.'.'.$model->main_image->extension;
				
	// 		}
			
	// 		$model->created = date('Y-m-d h:i:s');
			
	// 		$model->save();
			
	// 		// save user logs data in user_logs table
	// 		$logs_model = new Logs();
			
	// 		$user_logs = array('model'=>'Deals','action'=>'Update','activity' => $model->title.' is added','action_id'=>$model->id);
	// 		$logs_model->saveUserLogs($user_logs);
			
	// 		Yii::$app->session->setFlash('success', 'Deals is successfully saved');
    //         return $this->redirect(['index']);
    //     } else {
    //         return $this->render('update', [
    //             'model' => $model,
    //         ]);
    //     }
    // }

    // /**
    //  * Deletes an existing Deals model.
    //  * If deletion is successful, the browser will be redirected to the 'index' page.
    //  * @param integer $id
    //  * @return mixed
    //  */
    // public function actionDelete($id)
    // {
    //     $model = $this->findModel($id);
		
	// 	$this->findModel($id)->delete();
		
	// 	// save user logs data in user_logs table
	// 		$logs_model = new Logs();
			
	// 		$user_logs = array('model'=>'Deals','action'=>'Delete','activity' => $model->title.' is deleted','action_id'=>$model->id);
	// 		$logs_model->saveUserLogs($user_logs);	
                        
    //         Yii::$app->session->setFlash('success', 'Deals is successfully delete');

    //     return $this->redirect(['index']);
    // }

    /**
     * Finds the Deals model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Deals the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Coupons::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }



	  public function actionMove()
    {
       $selection_data = (array)Yii::$app->request->post('selection');//typecasting

        if (!empty($selection_data)) {
            //echo '<pre>'; print_r($selection_data); die;
            foreach ($selection_data as $id) {

                $Coupons = new Deals();
                $couponsData = $Coupons::find()->where(['id' => $id])->one();

                if (!empty($couponsData)) {
						if($couponsData->moved){
							$couponsData->moved=0;
						}else{
							$couponsData->moved=1;
						}
                   $couponsData->save();

                }

            }
            Yii::$app->session->setFlash('success', 'Deals Moved Successfully');

            return $this->redirect(Yii::$app->request->referrer);

        }
		return $this->redirect(Yii::$app->request->referrer);
        
    }
	
	
    /**
    * Import Product Data
    */
	
	public function actionImportdata()
    {	
	

    	$model = new Deals();

    	if($model->load(Yii::$app->request->post())){
       
        $file = UploadedFile::getInstance($model,'file');
		
        $filename = 'Data-'.Date('YmdGis').'.'.$file->extension;
		
        $upload = $file->saveAs('uploads/deals_import/'.$filename);
		
		define('CSV_PATH','uploads/deals_import/'); 
		$csv_file = CSV_PATH . $filename;
			$row = 1;

trunk/frontend/controllers/DealsController.php
<?php
namespace frontend\controllers;

use common\models\ActivityTracker;
use Yii;
use yii\web\Controller;
use backend\models\CouponsSearch;
use common\models\Deals;
use backend\models\CouponsVendors;
use common\models\Coupons;
use yii\web\NotFoundHttpException;

/**
 * Deal controller
 */
class DealsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays deal listing page.
     *
     * @return mixed
     */
    public function actionIndex()
    {
		$list=CouponsVendors::getVendorsList();
        return $this->render('coupon',['list'=>$list]);
    }


	 public function actionMerchant()
    {

		 $merchant = Yii::$app->request->get('merchant');
		$list=CouponsVendors::getCouponsMerchant($merchant);
        return $this->render('coupon',['list'=>$list]);
    }


	 /**
     * Displays deal listing page.
     *
     * @return mixed
     */
    public function actionDeals()
    {
	
  $suppliers = Yii::$app->request->get('merchant');
$couponVendor=CouponsVendors::getVendorObj(  $suppliers );

 if(empty($couponVendor) ||  $couponVendor===null)
   	throw new \yii\web\NotFoundHttpException();

				$typeArray=array(
					
					'1'=>'Coupons',
					'2'=>'Cashback',
						'3'=>'Deals',
					
					);

 		$suppliers = $cats =$typeParam="";
  		$supplierArr = $catArr = $typeParamArr=[];
      
		$cats= Yii::$app->request->get('category');
		$typeParam= '1';
			   
		if(isset($cats)){
					$catArr = explode('-', $cats);
		}

		if(isset($typeParam)){
			$typeParamArr = explode('-', $typeParam);
		}

	$popupalarList=CouponsVendors::getVendorsList();			

	$categoryList=	Coupons::getCategoryList($couponVendor[0]['id'],$typeParamArr);
	$storeList=CouponsVendors::getListswithSlug();
	$type=Coupons::getOfferType();

$uds= Yii::$app->request->get('id');
if(isset($uds)){
	 $this->view->params['index'] = 'false';
}

	 if(!$couponVendor[0]['google_index']) {
                 $this->view->params['index'] = 'false';
        }

if(isset($cats)){
	 $this->view->params['index'] = 'false';
}
	
    	
    	   $searchModel  = new CouponsSearch();
		   $searchModel -> moved=0;
		   $searchModel -> type=0;
		   $paramsdata=Yii::$app->request->queryParams;
		    $paramsdata['id_merchant']=$couponVendor[0]['id'];
		   $dataProvider = $searchModel->search($paramsdata);




 \Yii::$app->view->registerMetaTag([
        	'name' => 'description',
        	'content' => $couponVendor[0]['meta_descrption'] ,
        ]);
        \Yii::$app->view->registerMetaTag([
        	'name' => 'keyword',
        	'content' => $couponVendor[0]['meta_keyword'] ,
        ]);

			return $this->render('index', [
				'searchModel'  => $searchModel,
				'dataProvider' => $dataProvider,
				'category'=>$categoryList,
				'storeList'=>$storeList,
				'catArr'=> $catArr,
				'merchantArray' =>  $couponVendor[0]['id'] ,
				'type'=>$type,
					'popular'=>$popupalarList,
				'typeArray'=>$typeArray,
				'typeParam'=>$typeParamArr,
				'couponVendor'=>$couponVendor,
			]);
        return $this->render('index',['category'=>$categoryList]);
    }
    
    public function actionFilter(){
    	\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    	
    	/*
    	current = 1 (+0 = (current-1)*2 ) = 7 =>  1-3,  4-7
    	current = 2 (+2 = (current-1)*2 ) = 14 => 4-6,  7-11
    	current = 3 (+4 = (current-1)*2 ) = 21 => 7-9, 10-13
    	current = 4 (+6 = (current-1)*2 ) = 28 => 10-12, 13-16
    	current = 5 (+8 = (current-1)*2 ) = 35 => 13-15, 16-19
    	*/
    	
    	$pageNumber = (int)\Yii::$app->request->get('page');
    	$supplierId = (int)\Yii::$app->request->get('id');
    	$dealSuppliers = Suppliers::topDiscountedSuppliers();
    	if($pageNumber <= 1)
    		$pageSize = 7;
    	else 
    		$pageSize = ($pageNumber - 1) * 2;
    	
    	$moreDealImages = []; $supplerData = $supplierName = null;
    	foreach($dealSuppliers as $supplier){
    		if($supplierId === $supplier->id){
    			$supplierData = $supplier;
    			$supplierName = $supplier->name;
	    		$query = Deals::getDealsBySupplierQuery($supplierId, (($pageSize+$pageNumber)-1), 8);
// 	    		$countQuery = clone $query;
// 	    		$pages = new \yii\data\Pagination(['defaultPageSize' => $pageSize, 'totalCount' => $countQuery->count()]);
// 	    		$models = $query->offset()
// 	    			->limit(7);
	    		
	    		$moreDealImages = $query->all();
    		}
    	}
    	
    	return [
    		'meta' => ['status' => 200, 'message' => 'All good'], 
    		'data' => ['html' => $this->renderPartial('dealsData',['dealsData' => $moreDealImages, 
    					'supplier' => $supplierData, 'pageNumber' => $pageNumber]), 'id' => $supplierName,
    		]
    	];
    }

    private function findCouponById($id)
    {
        if (($model = Coupons::find()->where(['track_id' => $id])->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionStoreOut($id)
    {
        $this->layout = "track";
        $coupon = $this->findCouponById($id);
        $url = $coupon->link;
        $sessionId = Yii::$app->session->id;
        $activityType = ActivityTracker::Activity_COUPON;
        $storeName = $coupon->vendors->name;
        ActivityTracker::saveActivity($url, $sessionId, $activityType, $storeName);
        return $this->render("//product/send_to_store", [
            'url' => $url
        ]);
    }
}

trunk/backend/views/deals/_form.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;
use kartik\select2\Select2;
use common\models\Suppliers;

/* @var $this yii\web\View */
/* @var $model backend\models\Deals */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="deals-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?php
		echo $form->field($model, 'store_id')->widget(Select2::classname(), [
			'data' => ArrayHelper::map(Suppliers::find()->all(),'id','name'),
			'language' => 'eg',
			'options' => ['placeholder' => 'Select Store'],
			'pluginOptions' => [
				'allowClear' => true
			],
		]);
	?>

    <?= $form->field($model, 'brand')->textInput() ?>
	
	<?= $form->field($model, 'link')->textInput() ?>
	
	<?php echo  $form->field($model, 'main_image')->fileInput(['accept' => 'image/*']); ?>
	
	<?php if ($model->image): ?>
	
        <div class="form-group">
		<?php 
				//$path = str_replace('admin','frontend/web/',Yii::$app->getUrlManager()->getBaseUrl());
				$path = '/';
			?>
			<?php echo Html::img($path.'uploads/deals/'.$model->image,['class'=>'img-responsive  img-thumbnail small-thumbnail','alt'=>'Deal Image']); ?>
           
        </div>
		
    <?php endif; ?>
	
	<?= $form->field($model, 'price')->textInput() ?>
	
	<?= $form->field($model, 'offer_price')->textInput() ?>
	
	<?= $form->field($model, 'discount')->textInput() ?>
	
	<?php echo  $form->field($model, 'start_date')->textInput(['id' => 'start_date']) ?>
	
	<?php echo  $form->field($model, 'end_date')->textInput(['id' => 'end_date']) ?>
	
	<?= $form->field($model, 'availability')->textInput() ?>
	
	<?= $form->field($model, 'sizes')->textInput() ?>
	
	<?php echo $form->field($model, 'description')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic'
    ]) ?>


   <?php echo  $form->field($model, 'status')->dropDownList([ 'active' => 'Active', 'inactive' => 'Inactive', ]) ?>

    

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

trunk/backend/views/deals/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\DealsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="deals-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'product_id') ?>

    <?= $form->field($model, 'discount') ?>

    <?= $form->field($model, 'start_date') ?>

    <?php // echo $form->field($model, 'end_date') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

trunk/backend/views/deals/create.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $model backend\models\Deals */

$this->title = 'Create Deals';
$this->params['breadcrumbs'][] = ['label' => 'Deals', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="deals-create">

    <section class="content-header">
	   <h1><?php echo  Html::encode($this->title) ?></h1>
	  <?php echo Breadcrumbs::widget([
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
</section>
<section class="content">	
	
	  <div class="box box-info">
			 <div class="box-body">	
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>
			 <div class="box-footer">&nbsp;</div>
	</div>

</section>
</div>

trunk/backend/views/deals/importdata.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;


$this->title = 'Import Deals Data';
$this->params['breadcrumbs'][] = ['label' => 'Deals', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
	   <h1><?php echo  Html::encode($this->title) ?></h1>
	  <?php echo Breadcrumbs::widget([
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
</section>

<section class="content">	
	
	  <div class="box box-info">
	  	<div class="box-body">	
			<?php $form = ActiveForm::begin(['options' => ['enctype'=>'multipart/form-data']]); ?>
		    <?php echo  $form->field($model,'file')->fileInput()->label('Deals Import csv file') ?>
			
		   
		    <div class="form-group">
		        <?= Html::submitButton('Save',['class'=>'btn btn-primary']) ?>
		    </div>
		<?php ActiveForm::end(); ?>
		</div>
	</div>

</section>

trunk/backend/views/deals/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Breadcrumbs;

use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use common\models\Suppliers;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\DealsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Deals';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="deals-index">

    <section class="content-header">
	   <h1><?php echo  Html::encode($this->title) ?></h1>
	  <?php echo Breadcrumbs::widget([
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
</section>
	
	<section class="content">
	<div class="row">
	<div class="col-xs-12">
	<div class="box">
<div class="box-header">
    
					<!--<?php echo  Html::a('Download Csv Format', ['download_deals_csv_format'], ['class' => 'btn btn-success','style' => 'float:right']) ?>
					
					<?php echo  Html::a('Export', ['export'], ['class' => 'btn btn-success','style' => 'float:right']) ?>
					<?php echo  Html::a('Import', ['importdata'], ['class' => 'btn btn-success','style' => 'float:right']) ?> --->
				 <?php echo  Html::a('Run Scrapper', ['scraper'], ['class' => 'btn btn-success','style' => 'float:right','target'=>'_blank']) ?>
                <p> <?php echo  Html::a('Create Deals', ['create'], ['class' => 'btn btn-success','style' => 'float:right']) ?>
    </p>
	
	</div>
	
				
				<?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
	
	<?php 
			
			$store_id = '';
			if(isset($_GET['DealsSearch'])){
				$store_id = $_GET['DealsSearch']['store_id'];
			}
	?>
	<div class="searchblock">
	<div class="col-sm-2 col-lg-2 col-md-2  col-xs-12">
	<?php
		// Normal select with ActiveForm & model
		$model->store_id = $store_id;
		echo $form->field($model, 'store_id')->widget(Select2::classname(), [
			'data' => ArrayHelper::map(Suppliers::find()->andWhere(['!=', 'is_delete' ,1])->all(),'id','name'),
			'language' => 'eg',
			'options' => ['placeholder' => 'Select Store','id' => 'store_id'],
			'pluginOptions' => [
				'allowClear' => true
			],
		]);
	?>
	</div>
	
	 <div class="col-sm-2 col-lg-2 col-md-2 col-xs-12">
<div class="form-group" style="margin-top:24px;">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary btn-block']) ?>
    </div></div>
	</div>
	<?php ActiveForm::end() ?>
    <div class="clearfix"></div>
	
	
<div class="box-body">
<?=Html::beginForm(['deals/move'],'post');?>
<?=Html::submitButton('Move Deals', ['class' => 'btn btn-primary pull-right',]);?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

           // 'id',
           
			[
				'attribute'=>'title',
			    'content'=> function($data){
				 return substr($data->title, 0, 50);
				}
		     ],
            'price',
            'offer_price',
            'store_id',
            // 'end_date',
             'status',
             'created',
			[
			 	//'label'=>'sort down',
			 	'format' => 'raw',
                // here comes the problem - instead of parent_region I need to have parent
                'value' => function ($dataProvider) {
                     return Html::a('<i class="fa fa-eye" aria-hidden="true"></i>', $dataProvider->link, ['target'=>'_blank']);
                 },
             ],
            [
			'class' => 'yii\grid\ActionColumn',
			'template' => '{update} {delete}',
			],
			[
			'class' => 'yii\grid\CheckboxColumn',
				'checkboxOptions' => function ($dataProvider) {
					
						return ['value'=>$dataProvider->id];
					
					
				} 
			]
        ],
    ]); ?>
	<?= Html::endForm();?> 
</div>
</div>
</div>
</div>
</div>
</section>

trunk/backend/views/deals/update.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $model backend\models\Deals */

$this->title = 'Update Deals: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Deals', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="deals-update">

    <section class="content-header">
	   <h1><?php echo  Html::encode($this->title) ?></h1>
	  <?php echo Breadcrumbs::widget([
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
</section>
<section class="content">	
	
	  <div class="box box-info">
			 <div class="box-body">	
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>
			 <div class="box-footer">&nbsp;</div>
	</div>

</section>
</div>

trunk/backend/views/deals/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Deals */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Deals', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="deals-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'product_id',
            'discount',
            'start_date',
            'end_date',
            'status',
            'created',
        ],
    ]) ?>

</div>