trunk/common/models/Coupons.php
<?php
namespace common\models;


use Yii;
use backend\models\CouponsVendors;
use yii\helpers\Url;

/**
 * This is the model class for table "coupons".
 *
 * @property integer $id
 * @property string $title
 * @property string $sub_title
 * @property string $offer
 * @property string $description
 * @property string $valid
 * @property string $status
 * @property string $created
 * @property integer $moved
 * @property integer discount
 * @property integer type
 */
class Coupons extends \yii\db\ActiveRecord
{
	public $file;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'coupons';
    }


    public function fields()
    {
        $fields = parent::fields();
        $extraFields= [
           

            'redirectLink' => function ($model) {

                return \Yii::$app->params['frontend'].$model->track_link;
            },

          
       
        ];
        
        return array_merge( $fields,$extraFields);
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['merchant','title','link'],'required'],
            [[ 'discount', 'moved', 'type', 'created','offer_id','promo_id','offer_type','code','category','offer_url','start_date','expiry_date','featured','exclusive','ref_id','link','store_link','meta_title','meta_description','meta_keywords','verified_on','call_to_action_button','track_link','track_id'], 'safe'],
            [['title', 'sub_title', 'offer','api_name','merchant_logo_url'], 'string', 'max' => 255],
            [['valid'], 'string', 'max' => 25],
            [['status'], 'string', 'max' => 10],
			[['file'],'file','extensions'=>'csv','maxSize'=>1024 * 1024 * 5],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'sub_title' => 'Sub Title',
            'offer' => 'Offer',
            'description' => 'Description',
            'valid' => 'Valid',
            'status' => 'Status',
            'created' => 'Created',
            'track_link'=>'Share Link'
        ];
    }
	
    /*
     * Get Coupon category
     */
      public function getCategoryobj() {
        return $this->hasOne(CouponCategories::className(), ['id' => 'category']);
    }

    public static function getFieldsArray(){
    	return [
	    	'id',
	    	'offer_id',
	    	'promo_id',
	    	'title',
	    	'sub_title',
	    	'offer',
	    	'offer_type',
	    	'code',
	    	'category',
	    	'offer_url',
	    	'start_date',
	    	'expiry_date',
	    	'featured',
	    	'exclusive',
	    	'ref_id',
	    	'link',
	    	'store_link',
	    	'description',
	    	'valid',
	    	'status',
	    	'created',
    	];
    }



public function getVendors()
{
    return $this->hasOne(CouponsVendors::className(), ['id' => 'merchant']);
}

public static function getCategoryList($supplier,$type){
    
$where="";
if(isset($supplier)){
     
    $where=" and merchant  = ".$supplier." ";
}

if(!empty($type) && count($type)>0 && !empty($type[0])){
 
  
    $where.=" and type  IN (". implode(',',$type).") ";
}


$connection = Yii::$app->getDb();
$command = $connection->createCommand("
    SELECT count(*) as count, d.category, cc.name FROM `coupons` as d  left join coupon_categories cc on cc.id=d.category where d.status='active'  ".$where." group by category order by count(*) desc");

$result = $command->queryAll();
	
		return $result;
}
	

public static function getStoreList($cat,$type){
$where="";

if(!empty($cat)  && count($cat)>0 && !empty($cat[0])){
 
    $where=" and category  IN (".implode(',',$cat).") ";
}


if(!empty($type) && count($type)>0 && !empty($type[0])){
 
  
    $where=" and type  IN (". implode(',',$type).") ";
}


$connection = Yii::$app->getDb();
$command = $connection->createCommand("
     SELECT count(*) as count, d.merchant FROM `coupons` as d  where status='active'  ".$where." group by merchant order by count(*) desc;");

$result = $command->queryAll();
	
		return $result;
}

public static function getOfferRange(){

    $sql="select discount div 10 as discountList, count(*) as count from coupons where discount>0 group by discountList;";

$connection = Yii::$app->getDb();
$command = $connection->createCommand("
     $sql");

$result = $command->queryAll();
	
		return $result;

}

public static function getOfferType(){

    $sql="select type, count(*) as count from coupons   group by type;";

$connection = Yii::$app->getDb();
$command = $connection->createCommand("
     $sql");

$result = $command->queryAll();
	
		return $result;

}


public static function deleteOldDeals(){

      $sql="delete from coupons where expiry_date=".date('Y-m-d');

$connection = Yii::$app->getDb();
$command = $connection->createCommand("
     $sql");

$result = $command->execute();
	
		return $result;

}

    public function getStoreLink()
    {
        
        if (empty($this->track_id)) {
            $this->track_id = md5($this->id);
            $this->save(false);
        }
        return Url::toRoute(['/deals/store-out', 'id' => $this->track_id]);
    }



    public function getLastestCoupons(){

        $sql = " select cv.slug,c.call_to_action_button, c.type, cv.image,cv.name,c.title, discount, code, link,c.id, c.description from coupons c left join coupons_vendors cv on cv.id=c.merchant  group by name order by verified_on desc limit 8";
        
        $connection = Yii::$app->getDb();
        $command = $connection->createCommand($sql);
        $result = $command->queryAll();

      
	    return $result;

    }

}

trunk/backend/controllers/CouponsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Coupons;
use backend\models\CouponsSearch;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use backend\models\Logs;
use yii\web\UploadedFile;
use common\models\CouponCategories;
use backend\models\CouponsVendors;

/**
 * CouponsController implements the CRUD actions for Coupons model.
 */
class CouponsController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post','scraper'],
                ],
            ],
        ];
    }

    



	 public function actionIndex()
    {
        $searchModel = new CouponsSearch();
	
	    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


public function actionUploadFile()
    {
           $module = Yii::$app->getModule('articles');
        $imagePath = '/uploads/coupons/cms/';
        $imagePathUrl = '/uploads/coupons/cms/';
        $imgName = time();
        $fileField = "upload";
		$path = Yii::getAlias('@frontend') .'/web/';

        $file = UploadedFile::getInstanceByName($fileField);
        $message = '';
        $url = '';
        if (is_null($file)) {
            $message = 'Failed Upload File';
        } else {
            $fileExt = $file->extension;
            if ($fileExt != 'jpg' && $fileExt != 'jpeg' && $fileExt != 'png' && $fileExt != 'gif') {
                $message = "The image must be in either JPG, JPEG, GIF or PNG format.";
            } else {
                $file->name = $imgName . ".{$fileExt}";
                $image = $file->saveAs($path.$imagePath . $imgName . ".{$fileExt}");
                if ($image !== false) {
                    $url =  $module->frontPageUrl. $imagePathUrl . '/' . $file->name;
                } else {
                    $message = 'Success Upload Failure,Try again!';
                }
            }
        }
        $funcNum = $_GET ['CKEditorFuncNum'];
        echo "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction($funcNum, '$url', '$message');</script>";
    }


	 public function actionStage()
    {
        $searchModel = new CouponsSearch();
		$searchModel->moved = 0;
		$searchModel->type = 1;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Coupons model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Coupons model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Coupons();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			
				
						
			$model->created = date('Y-m-d h:i:s');

            if ($model->save()) {
                $model->track_link = $model->storeLink;
                $model->save();
            }
			
			// save user logs data in user_logs table
			$logs_model = new Logs();
			
			$user_logs = array('model'=>'Coupons','action'=>'Create','activity' => $model->title.' is added','action_id'=>$model->id);
			$logs_model->saveUserLogs($user_logs);
			
			Yii::$app->session->setFlash('success', 'Coupons is successfully saved');
            return $this->redirect(['index']);
			
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Coupons model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->created = date('Y-m-d h:i:s');

            if ($model->save()) {
                $model->track_link = $model->storeLink;
                $model->save();
            }
			
			// save user logs data in user_logs table
			$logs_model = new Logs();
			
			$user_logs = array('model'=>'Coupons','action'=>'Update','activity' => $model->title.' is added','action_id'=>$model->id);
			$logs_model->saveUserLogs($user_logs);
			
			Yii::$app->session->setFlash('success', 'Coupons is successfully saved');
			if($model->moved){
            return $this->redirect(['online']);
			}else{
				     return $this->redirect(['stage']);
			}
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Coupons model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
		
		$this->findModel($id)->delete();
		
		// save user logs data in user_logs table
			$logs_model = new Logs();
			
			$user_logs = array('model'=>'Coupons','action'=>'Delete','activity' => $model->title.' is deleted','action_id'=>$model->id);
			$logs_model->saveUserLogs($user_logs);	
                        
            Yii::$app->session->setFlash('success', 'Coupons is successfully delete');
		if($model->moved){
            return $this->redirect(['online']);
			}else{
				     return $this->redirect(['stage']);
			}
        
    }

	  public function actionMovecoupons()
    {
        $selection_data = (array)Yii::$app->request->post('selection');//typecasting

        if (!empty($selection_data)) {
            //echo '<pre>'; print_r($selection_data); die;
            foreach ($selection_data as $id) {

                $Coupons = new Coupons();
                $couponsData = $Coupons::find()->where(['id' => $id])->one();

                if (!empty($couponsData)) {
                   $couponsData->delete();

                }

            }
            Yii::$app->session->setFlash('success', 'Coupons Deleted Successfully');

            return $this->redirect(Yii::$app->request->referrer);

        }
        
    }


	

    /**
     * Finds the Coupons model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Coupons the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Coupons::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
	
	public function actionSave_coupons_api()
	{
		
		$apiurl = 'https://api.hasoffers.com/Apiv3/json?NetworkId=vcm&Target=Affiliate_Offer&Method=findAll&api_key=7588c21a58502cb238a908dd68cb03bc2f83d8884ab03b98e0e3ba861224d7ff';

         $data = json_decode(file_get_contents($apiurl), true);
       //  echo '<pre>'; print_r($data); die;
		 if(!empty($data['response']['data']) && isset($data['response']['data'])){
				
				foreach($data['response']['data'] as $dataline){
			 
				 $couponModel = new Coupons();
				 
				 $checkResult = $couponModel::find()->where(['offer_id' => $dataline['Offer']['id']])->one();
				
				 if(empty($checkResult))
				 {
					  $couponModel->title = $dataline['Offer']['name'];
					  $couponModel->offer_id = $dataline['Offer']['id'];
					  $couponModel->description = $dataline['Offer']['description'];
					  $couponModel->expiry_date = $dataline['Offer']['expiration_date'];
					  $couponModel->offer_url = $dataline['Offer']['preview_url'];
					  $couponModel->save(false);
				 }
			}  
		 }		
	}
	

	 
	/**
    * Import Product Data
    */

    public function actionImportdata()
    {	
    	$model = new Coupons();

    	if($model->load(Yii::$app->request->post())){
       
        $file = UploadedFile::getInstance($model,'file');
		
        $filename = 'Data-'.Date('YmdGis').'.'.$file->extension;
		
        $upload = $file->saveAs('uploads/coupons_import/'.$filename);
		
		define('CSV_PATH','uploads/coupons_import/'); 
		$csv_file = CSV_PATH . $filename;
			$row = 1;
			$charset = 'UTF-8';

			$errorstring=[];
			if (($handle = fopen($csv_file, "r")) !== FALSE) {
					while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
					
					if($row != 1){
						
						$couponsModel = new Coupons();
						
						$merchant = isset($data[0])?$data[0]:'';
						$category = isset($data[1])?$data[1]:'';

					if (!empty($merchant) && ($model = CouponsVendors::findOne($merchant)) !== null) {
						$couponsModel->merchant = isset($data[0])?$data[0]:'';
							$couponsModel->category = isset($data[1])?$data[1]:'';
							$couponsModel->title = isset($data[2])?$data[2]:'';

							
							$couponsModel->meta_title = isset($data[3])?$data[3]:'';
							if(mb_strlen($couponsModel->meta_title, $charset) > 70) {
 									$couponsModel->meta_title = mb_substr($couponsModel->meta_title, 0, 70, $charset);
							}
							$couponsModel->meta_description = isset($data[4])?$data[4]:'';

							if(mb_strlen($couponsModel->meta_description , $charset) > 160) {
 									$couponsModel->meta_description  = mb_substr($couponsModel->meta_description , 0, 160, $charset);
							}
							$couponsModel->meta_keywords = isset($data[5])?$data[5]:'';
							$couponsModel->link = isset($data[6])?$data[6]:'';
							$couponsModel->start_date = isset($data[7])?$data[7]:'';

trunk/backend/views/coupons/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;
use dosamigos\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model backend\models\Coupons */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="coupons-form">

    <?php $form = ActiveForm::begin(); ?>
	
	<?php echo  $form->field($model, 'offer')->textInput(['maxlength' => true]) ?>
	 
    <?php echo  $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?php echo  $form->field($model, 'sub_title')->textInput(['maxlength' => true]) ?>

   
	
	<?php echo  $form->field($model, 'offer_id')->textInput() ?>
	<?php echo  $form->field($model, 'promo_id')->textInput() ?>
	<?php echo  $form->field($model, 'offer_type')->textInput() ?>
	<?php echo  $form->field($model, 'code')->textInput() ?>
	<?php echo  $form->field($model, 'category')->textInput() ?>
	<?php echo  $form->field($model, 'offer_url')->textInput() ?>
	<?php echo  $form->field($model, 'start_date')->textInput(['id' => 'start_date']) ?>
	<?php echo  $form->field($model, 'expiry_date')->textInput(['id' => 'end_date']) ?>
	
	<?php echo  $form->field($model, 'featured')->textInput() ?>
	<?php echo  $form->field($model, 'exclusive')->textInput() ?>
	<?php echo  $form->field($model, 'ref_id')->textInput() ?>
	<?php echo  $form->field($model, 'link')->textInput() ?>
	<?php echo  $form->field($model, 'store_link')->textInput() ?>
	
    <?php echo $form->field($model, 'description')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'basic'
    ]) ?>


   <?php echo  $form->field($model, 'status')->dropDownList([ 'active' => 'Active', 'inactive' => 'Inactive', ]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

trunk/backend/views/coupons/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\CouponsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="coupons-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'merchant') ?>

    <?= $form->field($model, 'category') ?>


    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

trunk/backend/views/coupons/create.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use yii\widgets\ActiveForm;
use backend\models\MenuTypes;
use common\models\CouponCategories;
use backend\models\CouponsVendors;
use backend\models\Brands;
use backend\models\Menus;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use dosamigos\ckeditor\CKEditor;


/* @var $this yii\web\View */
/* @var $model backend\models\Coupons */

$this->title = 'Create '.Yii::$app->controller->id;
$this->params['breadcrumbs'][] = ['label' => Yii::$app->controller->id];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
	   <h1><?php echo  Html::encode($this->title) ?></h1>
	  <?php echo Breadcrumbs::widget([
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
</section>

<section class="content">	
	
	  <div class="box box-info">
			 <div class="box-body">	
			

<div class="coupons-form">

    <?php $form = ActiveForm::begin(); ?>
	
	<?php //echo  $form->field($model, 'merchant')->textInput() ?>


<?php
		// Normal select with ActiveForm & model
		$couponsVendors = new CouponsVendors();
		$vendors=  $couponsVendors->getLists();
		echo $form->field($model, 'merchant')->widget(Select2::classname(), [
			'data' => $vendors,
			'language' => 'eg',
			'options' => ['placeholder' => 'Select Merchant'],
			'pluginOptions' => [
				'allowClear' => true
			],
		]);
			
		
	?>

	


<?php
		// Normal select with ActiveForm & model
		$categoriesModel = new CouponCategories();
		$categories =  $categoriesModel->getCategoryLists();
		echo $form->field($model, 'category')->widget(Select2::classname(), [
			'data' => $categories,
			'language' => 'eg',
			'options' => ['placeholder' => 'Select Category'],
			'pluginOptions' => [
				'allowClear' => true
			],
		]);
			
		
	?>

	 <?php echo  $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

	<?php //echo  $form->field($model, 'offer')->textInput(['maxlength' => true]) ?>
	<?php echo  $form->field($model, 'meta_title')->textInput(['maxlength' => 70]) ?>
	 
   <?php echo  $form->field($model, 'meta_description')->textInput(['maxlength' => 160]) ?>
    <?php echo  $form->field($model, 'meta_keywords')->textInput(['maxlength' => true]) ?>

   	<?php echo  $form->field($model, 'link')->textInput() ?>
<?php echo  $form->field($model, 'start_date')->textInput(['id' => 'start_date']) ?>
	<?php echo  $form->field($model, 'expiry_date')->textInput(['id' => 'end_date']) ?>
	
<?php echo  $form->field($model, 'discount')->textInput() ?>

 <?php echo $form->field($model, 'featured')->checkBox(['label' => 'Featured', 'uncheck' => 0, 'checked' => 'checked']);  ?>
 <?php echo $form->field($model, 'exclusive')->checkBox(['label' => 'Exclusive', 'uncheck' => 0, 'checked' => 'checked']);  ?>


 <?php echo $form->field($model, 'description')->widget(CKEditor::className(), 
[


 'clientOptions' => [
 'filebrowserUploadUrl' => \yii\helpers\Url::to(['/coupons/upload-file']),
                                                
                                                'toolbarGroups' => [
                                                    ['name' => 'undo'],
                                                    ['name' => 'basicstyles', 'groups' => ['basicstyles', 'cleanup']],
                                                    ['name' => 'colors'],
                                                    ['name' => 'links', 'groups' => ['links', 'insert']],
                                                    ['name' => 'others', 'groups' => ['others', 'about']],
                                                    ['name' => 'styles'],
                                                    ['name' => 'document', 'groups' => ['mode', 'document']],
                                                    ['name' => 'videodetector'] // <--- OUR NEW PLUGIN YAY!
                                                ]],
                                            'options' => ['rows' => 6],
                                            'preset' => 'custom'








    ]) ?>

   <?php echo  $form->field($model, 'status')->dropDownList([ 'active' => 'Active', 'inactive' => 'Inactive', ]) ?>
<?php  echo  $form->field($model, 'code')->textInput();  ?>

 <?php echo  $form->field($model, 'type')->dropDownList([ '0' => 'Coupon', '1' => 'CashBack', '2' => 'Deals' ]) ?>

<?php echo  $form->field($model, 'verified_on')->textInput(['id' => 'verified_on']) ?>
	 	<?php echo  $form->field($model, 'call_to_action_button')->textInput() ?>
	<?php // echo  $form->field($model, 'offer_id')->textInput() ?>
	<?php //echo  $form->field($model, 'promo_id')->textInput() ?>
	<?php // echo  $form->field($model, 'offer_type')->textInput() ?>
	
	<?php // echo  $form->field($model, 'merchant')->textInput() ?>
	
		<?php // echo  $form->field($model, 'merchant_logo_url')->textInput() ?>
	




	<?php //echo  $form->field($model, 'offer_url')->textInput() ?>
	
	

	<?php //echo  $form->field($model, 'ref_id')->textInput() ?>

	<?php //echo  $form->field($model, 'store_link')->textInput() ?>
	
   

   
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

			</div>
			 <div class="box-footer">&nbsp;</div>
	</div>

</section>

trunk/backend/views/coupons/importdata.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Breadcrumbs;


$this->title = 'Import Coupons Data';
$this->params['breadcrumbs'][] = ['label' => 'Coupons', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
	   <h1><?php echo  Html::encode($this->title) ?></h1>
	  <?php echo Breadcrumbs::widget([
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
</section>

<section class="content">	
	
	  <div class="box box-info">
	  	<div class="box-body">	
			<?php $form = ActiveForm::begin(['options' => ['enctype'=>'multipart/form-data']]); ?>
		    <?php echo  $form->field($model,'file')->fileInput()->label('Coupons Import csv file') ?>
			
		   
		    <div class="form-group">
		        <?= Html::submitButton('Save',['class'=>'btn btn-primary']) ?>
		    </div>
		<?php ActiveForm::end(); ?>
		</div>
	</div>

</section>

trunk/backend/views/coupons/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\CouponsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::$app->controller->id;
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content-header">
	   <h1><?php echo  Html::encode($this->title) ?></h1>
	  <?php echo Breadcrumbs::widget([
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
</section>
<section class="content">
    
	<div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
					<?php echo  Html::a('Run Scrapper', ['coupons/scraper'], ['class' => 'btn btn-success','style' => 'float:right','target'=>'_blank']) ?>
					<?php echo  Html::a('Export', ['export'], ['class' => 'btn btn-success','style' => 'float:right']) ?>
					<?php echo  Html::a('Import', ['importdata'], ['class' => 'btn btn-success','style' => 'float:right']) ?>
				  <p><?php echo  Html::a('Create '.Yii::$app->controller->id, ['create'], ['class' => 'btn btn-success','style' => 'float:right']) ?></p>
                </div><!-- /.box-header -->
                <div class="box-body">


				<?=Html::beginForm(['coupons/movecoupons'],'post');?>
<?=Html::submitButton('Delete', ['class' => 'btn btn-primary pull-right',]);?>
     <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
           
			[
				'attribute'=>'title',
			    'content'=> function($data){
				 return substr($data->title, 0, 35);
				}
		     ],
            //'sub_title',
            'merchant',
			'category',
            //'description:ntext',
//			'start_date',
             'expiry_date',
             'status',
            'created',

            [
			'class' => 'yii\grid\ActionColumn',
			'template' => '{update} {delete}',
			],[
			'class' => 'yii\grid\CheckboxColumn',
				'checkboxOptions' => function ($dataProvider) {
					
						return ['value'=>$dataProvider->id];
					
					
				} 
			]
        ],
    ]); ?>
	<?= Html::endForm();?> 
	</div>
	</div>
	</div>

</div>
</section>